List<String> mumbaiRailwayStations = [
  'Airoli',
  'Aman Lodge',
  'Ambernath',
  'Ambivli',
  'Andheri',
  'Apta',
  'Asangaon',
  'Atgaon',
  'Badlapur',
  'Bamandongri',
  'Bandra',
  'Bhandup',
  'Bhayandar',
  'Bhivpuri Road',
  'Bhiwandi Road',
  'Boisar',
  'Borivali',
  'Byculla',
  'CBD Belapur',
  'Charni Road',
  'Chembur',
  'Chhatrapati Shivaji Terminus',
  'Chikhale',
  'Chinchpokli',
  'Chouk',
  'Chunabhatti',
  'Churchgate',
  'Cotton Green',
  'Currey Road',
  'Dadar',
  'Dahanu Road',
  'Dahisar',
  'Dativali',
  'Dighe',
  'Diva Junction',
  'Dockyard Road',
  'Dolavli',
  'Dombivli',
  'Ghansoli',
  'Ghatkopar',
  'Goregaon',
  'Govandi',
  'Grant Road',
  'Guru Tegh Bahadur Nagar',
  'Hamrapur',
  'Jite',
  'Jogeshwari',
  'Juchandra',
  'Juinagar',
  'Jummapatti',
  'Kalamboli',
  'Kalwa',
  'Kalyan Junction',
  'Kaman Road',
  'Kandivli',
  'Kanjurmarg',
  'Karjat',
  'Kasara',
  'Kasu',
  'Kelavli',
  'Kelve Road',
  'Khadavli',
  'Khandeshwar',
  'Khar Road',
  'Kharbao',
  'Khardi',
  'Kharghar',
  'Kharkopar',
  'Khopoli',
  "King's Circle",
  'Kopar',
  'Kopar Khairane',
  'Kurla',
  'Lower Parel',
  'Lowjee',
  'Mahalaxmi',
  'Mahim Junction',
  'Malad',
  'Mankhurd',
  'Mansarovar',
  'Marine Lines',
  'Masjid',
  'Matheran',
  'Matunga',
  'Matunga Road',
  'Mira Road',
  'Mohope',
  'Mulund',
  'Mumbai Central',
  'Mumbra',
  'Nagothane',
  'Nahur',
  'Naigaon',
  'Nallasopara',
  'Navde Road',
  'Neral Junction',
  'Nerul',
  'Nidi',
  'Nilaje',
  'Palasdari',
  'Palghar',
  'Panvel',
  'Parel',
  'Pen',
  'Prabhadevi',
  'Rabale',
  'Ram Mandir',
  'Rasayani',
  'Reay Road',
  'Roha',
  'Sandhurst Road',
  'Sanpada',
  'Santacruz',
  'Saphale',
  'Seawoods–Darave',
  'Sewri',
  'Shahad',
  'Shelu',
  'Sion',
  'Somtane',
  'Taloje Panchnand',
  'Thakurli',
  'Thane',
  'Thansit',
  'Tilak Nagar',
  'Titwala',
  'Turbhe',
  'Ulhasnagar',
  'Umbermali',
  'Umroli',
  'Vadala Road',
  'Vaitarna',
  'Vangani',
  'Vangaon',
  'Vasai Road',
  'Vashi',
  'Vasind',
  'Vidyavihar',
  'Vikhroli',
  'Vile Parle',
  'Virar',
  'Vithalwadi',
  'Water Pipe',
  'Dronagiri',
  'Gavan',
  'Nhava Sheva',
  'Ranjanpada',
  'Sagar Sangam',
  'Targhar',
  'Uran City',
];
