name: CI

on:
  push:
    paths:
      - ".github/workflows/**"
      - "lib/**"
      - "android/**"
      - "ios/**"
      - "web/**"
      - "pubspec.yaml"

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.pub-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: "21"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.1"
          channel: "stable"

      - name: Setup project
        shell: bash
        env:
          FIREBASE_OPTIONS: ${{ vars.FIREBASE_OPTIONS }}
          GOOGLE_JSON_DATA: ${{ vars.GOOGLE_SERVICES }}
          GRADLE_OPTS: -Xmx4096m
        run: |
          mv lib/firebase_options.example.dart lib/firebase_options.dart

          if [ -z "$GOOGLE_JSON_DATA" ]; then
            cp android/app/google-services.mock.json android/app/google-services.json
          else
            echo "$GOOGLE_JSON_DATA" > android/app/google-services.json
          fi
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Build debug apk
        run: |
          flutter build apk --debug
          echo "Debug APK build complete"
